apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: caldiy-app-secret
  namespace: caldiy
  annotations:
    argocd.argoproj.io/sync-wave: "30"
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-cluster
  target:
    name: caldiy-app-secret
    template:
      engineVersion: v2
      data:
        DATABASE_URL: "postgresql://caldiy:{{ .dbpassword }}@caldiy-db-rw.caldiy.svc.cluster.local:5432/caldiy"
        DATABASE_DIRECT_URL: "postgresql://caldiy:{{ .dbpassword }}@caldiy-db-rw.caldiy.svc.cluster.local:5432/caldiy"
        NEXTAUTH_SECRET: "{{ .nextauth_secret }}"
        CALENDSO_ENCRYPTION_KEY: "{{ .encryption_key }}"
        CRON_API_KEY: "{{ .cron_api_key }}"
        EMAIL_SERVER_HOST: "{{ .smtp_host }}"
        EMAIL_SERVER_PORT: "465"
        EMAIL_SERVER_USER: "{{ .smtp_user }}"
        EMAIL_SERVER_PASSWORD: "{{ .smtp_password }}"
        EMAIL_FROM: "{{ .smtp_from }}"
  data:
    - secretKey: dbpassword
      remoteRef:
        key: CALDIY_POSTGRES_USER_PASSWORD
    - secretKey: nextauth_secret
      remoteRef:
        key: CALDIY_NEXTAUTH_SECRET
    - secretKey: encryption_key
      remoteRef:
        key: CALDIY_CALENDSO_ENCRYPTION_KEY
    - secretKey: cron_api_key
      remoteRef:
        key: CALDIY_CRON_API_KEY
    - secretKey: smtp_host
      remoteRef:
        key: MAIL_HOST
    - secretKey: smtp_user
      remoteRef:
        key: MAIL_USERNAME
    - secretKey: smtp_password
      remoteRef:
        key: MAIL_PASSWORD
    - secretKey: smtp_from
      remoteRef:
        key: MAIL_FROM
