apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - anyuid-rolebinding.yaml
  - external-secret-app.yaml
  - external-secret-db.yaml
  - caldiy-chart-app.yaml
  - namespace.yaml
  - postgresql-database.yaml
