apiVersion: machineconfiguration.openshift.io/v1
kind: KubeletConfig
metadata:
  name: set-max-pods
spec:
  autoSizingReserved: true
  machineConfigPoolSelector:
    matchLabels:
      increased-max-pods: enabled
  kubeletConfig:
    podsPerCore: 11
    maxPods: 352
