apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: devland-editor-agent-db-devland-secret
  namespace: devland
  annotations:
    argocd.argoproj.io/sync-wave: "30"
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-cluster
  target:
    name: devland-editor-agent-db-devland-secret
    template:
      engineVersion: v2
      type: kubernetes.io/basic-auth
      data:
        username: "devland_editor_agent"
        password: "{{ .password }}"
  data:
    - secretKey: password
      remoteRef:
        key: DEVLAND_EDITOR_AGENT_POSTGRES_USER_PASSWORD
