apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: devland-editor-agent-history-db
  namespace: devland
  labels:
    app.kubernetes.io/name: devland-editor-agent
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: lvms-vg1
  resources:
    requests:
      storage: 1Gi
