apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - externalsecret.yaml
  - external-ghcr-pull.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - route.yaml

images:
  - name: ghcr.io/pixeljonas/devland-editor-agent
    newName: ghcr.io/pixeljonas/devland-editor-agent
    digest: sha256:f69204840e451d5151d9af9c8800fc3a759231a34783ca4de07ca894d7ca6e96
