apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - externalsecret.yaml
  - external-ghcr-pull.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - route.yaml

images:
  - name: ghcr.io/pixeljonas/devland-editor-agent
    newName: ghcr.io/pixeljonas/devland-editor-agent
    digest: sha256:4157aeea040f64198e7fc7bf75ba2b47578353ba9294c19f1b1e19149bd7db94
