apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - externalsecret.yaml
  - external-ghcr-pull.yaml
  - pvc.yaml
  - history-db-pvc.yaml
  - deployment.yaml
  - service.yaml
  - route.yaml
  - backup

images:
  - name: ghcr.io/pixeljonas/devland-editor-agent
    newName: ghcr.io/pixeljonas/devland-editor-agent
    digest: sha256:dd5ff77017a6e0ae8b984892ee7cf51682ea4e49446ec776dd552a711dca3444
