apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: doppler-cluster
spec:
  provider:
    doppler:
      auth:
        secretRef:
          dopplerToken:
            name: eso-token-cluster
            key: dopplerToken
            namespace: external-secrets-operator
