apiVersion: v1
kind: Namespace
metadata:
  name: cloudnative-pg-operator
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    openshift.io/display-name: cloudnative-pg Operator
    openshift.io/description: >-
      A project to host the cloudnative-pg Operator so that it may be managed and upgraded separately from other
      operators.
  labels:
    openshift.io/cluster-monitoring: "true"
