apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - anyuid-rolebinding.yaml
  - external-honcho-credentials.yaml
  - external-honcho-db-honcho.yaml
  - external-honcho-db-connection.yaml
  - honcho-config.yaml
  - postgresql-database.yaml
  - honcho-app.yaml
