apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - external-recordbuddy-worker-secret.yaml
  - external-recordbuddy-worker-ghcr-pull.yaml
  - recordbuddy-worker-app.yaml
