apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - immich-chart.yaml
  - external-immich-credentials.yaml
  - anyuid-rolebinding.yaml
  - privileged-rolebinding.yaml
  - immich-nfs-pvs.yaml
  - ../../backup

patches:
  - target:
      kind: PersistentVolumeClaim
      name: database-syno-db-backup
    patch: |-
      - op: replace
        path: /spec/storageClassName
        value: lvms-vg1
