apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: external-hermes-credentials
  namespace: hermes-user1
  annotations:
    argocd.argoproj.io/sync-wave: "30"
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-cluster
  target:
    name: hermes-credentials
  data:
    - secretKey: OPENAI_API_KEY
      remoteRef:
        key: HERMES_USER1_LITELLM_API_KEY
    - secretKey: HONCHO_API_KEY
      remoteRef:
        key: HERMES_USER1_HONCHO_API_KEY
    - secretKey: API_SERVER_KEY
      remoteRef:
        key: HERMES_USER1_API_SERVER_KEY
