apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - anyuid-rolebinding.yaml
  - external-hermes-credentials.yaml
  - hermes-config.yaml
  - hermes-app.yaml
