apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: firefly-pguser-firefly
  namespace: firefly
  labels:
    postgres-operator.crunchydata.com/cluster: firefly
    postgres-operator.crunchydata.com/pguser: firefly
  annotations:
    argocd.argoproj.io/sync-wave: "30"
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-cluster
  target:
    name: firefly-pguser-firefly
    template:
      type: kubernetes.io/tls
      engineVersion: v2
      data:
        password: "{{ .password }}"
        verifier: ""
  data:
    - secretKey: password
      remoteRef:
        key: FIREFLY_POSTGRES_USER_PASSWORD
