apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: firefly-db-postgres-secret
  namespace: firefly
  annotations:
    argocd.argoproj.io/sync-wave: "30"
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-cluster
  target:
    name: firefly-db-postgres-secret
    template:
      engineVersion: v2
      type: kubernetes.io/basic-auth
      data:
        username: "postgres"
        password: "{{ .password }}"

  data:
    - secretKey: password
      remoteRef:
        key: FIREFLY_POSTGRES_POSTGRES_PASSWORD
