apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: firefly-pguser-firefly
  namespace: firefly
  annotations:
    argocd.argoproj.io/sync-wave: "30"
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-cluster
  target:
    name: firefly-db-pguser-firefly
    template:
      engineVersion: v2
      metadata:
        labels:
          postgres-operator.crunchydata.com/cluster: firefly-db
          postgres-operator.crunchydata.com/pguser: firefly
      data:
        password: "{{ .password }}"
        verifier: ""
  data:
    - secretKey: password
      remoteRef:
        key: FIREFLY_POSTGRES_USER_PASSWORD
