kind: SGCluster
apiVersion: stackgres.io/v1
metadata:
  name: firefly-db
  namespace: firefly
spec:
  instances: 1
  sgInstanceProfile: "size-small"
  nonProductionOptions:
    disableClusterPodAntiAffinity: true
  pods:
    persistentVolume:
      size: 10Gi
  postgres:
    version: latest
  initialData:
    scripts:
      - name: create-database-user
        scriptFrom:
          secretKeyRef:
            name: firefly-initial-data
            key: initial-data.sql
