kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: firefly-importer-pvc
  namespace: firefly
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Mi
  volumeMode: Filesystem
