kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: paperless-anyuid
  annotations:
    argocd.argoproj.io/sync-wave: "30"
subjects:
  - kind: ServiceAccount
    name: default
    namespace: paperless
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: "system:openshift:scc:anyuid"
