apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: paperless-db-paperless-secret
  namespace: paperless
  annotations:
    argocd.argoproj.io/sync-wave: "30"
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-cluster
  target:
    name: paperless-db-paperless-secret
    template:
      engineVersion: v2
      type: kubernetes.io/basic-auth
      data:
        username: "paperless"
        password: "{{ .password }}"

  data:
    - secretKey: password
      remoteRef:
        key: PAPERLESS_POSTGRES_USER_PASSWORD
