apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: external-paperless-secret-key
  namespace: paperless
  annotations:
    argocd.argoproj.io/sync-wave: "30"
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-cluster
  target:
    name: paperless-secret-key
  data:
    - secretKey: secret-key
      remoteRef:
        key: PAPERLESS_SECRET_KEY
