apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: paperless-db
  namespace: paperless
  annotations:
    argocd.argoproj.io/sync-wave: "100"
spec:
  instances: 1
  enablePDB: false

  bootstrap:
    initdb:
      database: paperless
      owner: paperless
      secret:
        name: paperless-db-paperless-secret

  storage:
    size: 20Gi
