apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vaultwarden-db-vaultwarden-secret
  namespace: vaultwarden
  annotations:
    argocd.argoproj.io/sync-wave: "30"
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-cluster
  target:
    name: vaultwarden-db-vaultwarden-secret
    template:
      engineVersion: v2
      type: kubernetes.io/basic-auth
      data:
        username: "vaultwarden"
        password: "{{ .password }}"

  data:
    - secretKey: password
      remoteRef:
        key: VAULTWARDEN_POSTGRES_USER_PASSWORD
