apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: vaultwarden-db
  namespace: firefly
spec:
  postgresVersion: 16
  instances:
    - name: vaultwarden-db
      dataVolumeClaimSpec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
  users:
    - name: vaultwarden
      databases:
        - vaultwarden
    - name: postgres