apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vaultwarden-backup-app
  namespace: openshift-gitops
spec:
  destination:
    namespace: vaultwarden
    server: https://kubernetes.default.svc
  project: cluster-apps
  source:
    path: components-apps/vaultwarden/backup
    repoURL: https://github.com/pixeljonas/cluster-gitops.git
    targetRevision: master
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
