apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "111"
  name: vaultwarden-app
  namespace: openshift-gitops
spec:
  destination:
    namespace: vaultwarden
    server: "https://kubernetes.default.svc"
  source:
    chart: app-template
    repoURL: https://bjw-s-labs.github.io/helm-charts
    targetRevision: 4.3.0
    helm:
      values: |-

        controllers:
          vaultwarden:
            containers:
              vaultwarden:
                image:
                  repository: vaultwarden/server
                  tag: 1.34.3
                  pullPolicy: IfNotPresent
                env:
                  TZ: Europe/Berlin
                  DATA_FOLDER: "config"   
                  ROCKET_PORT: 8000         
                  DATABASE_URL:
                    valueFrom:
                      secretKeyRef:
                        name: vaultwarden-credentials
                        key: db-url
                  ADMIN_TOKEN:
                    valueFrom:
                      secretKeyRef:
                        name: vaultwarden-credentials
                        key: admin-password
                securityContext:
                  privileged: true


        service:
          vaultwarden:
            controller: vaultwarden
            ports:
              http:
                port: 8000
              websocket:
                enabled: true
                port: 3012

        ingress:
          vaultwarden:
            enabled: true
            className: openshift-default
            annotations:
              route.openshift.io/termination: "edge"
            hosts:
              - host: vaultwarden.apps.altus.janz.digital
                paths:
                  - path: /
                    service:
                      identifier: vaultwarden
                      port: http

        persistence:
          config:
            suffix: config
            globalMounts:
              - path: /config
            storageClass: lvms-vg1
            accessMode: ReadWriteOnce
            size: 1Gi

  project: cluster-apps
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
