apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - external-recordbuddy-worker-de-secret.yaml
  - external-recordbuddy-worker-de-ghcr-pull.yaml
  - external-recordbuddy-worker-de-hf-token.yaml
  - recordbuddy-worker-de-app.yaml
