apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-storage

resources:
  - namespace.yaml
  - nfs-provisioner-app.yaml
  - nfs-backup-provisioner-app.yaml
  - storageclass-nfs-custom.yaml
