apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: external-qdrant-credentials
  namespace: qdrant
  annotations:
    argocd.argoproj.io/sync-wave: "30"
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-cluster
  target:
    name: qdrant-credentials
  data:
    - secretKey: QDRANT_API_KEY
      remoteRef:
        key: QDRANT_API_KEY
