apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: external-litellm-credentials
  namespace: litellm
  annotations:
    argocd.argoproj.io/sync-wave: "30"
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-cluster
  target:
    name: litellm-credentials
  data:
    - secretKey: LITELLM_MASTER_KEY
      remoteRef:
        key: LITELLM_MASTER_KEY
    - secretKey: gcp-credentials.json
      remoteRef:
        key: LITELLM_GCP_CREDENTIALS
    - secretKey: VERTEX_PROJECT_ID
      remoteRef:
        key: LITELLM_VERTEX_PROJECT_ID
