apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: litellm-db
  namespace: litellm
  annotations:
    argocd.argoproj.io/sync-wave: "100"
spec:
  instances: 1
  enablePDB: false
  bootstrap:
    initdb:
      database: litellm
      owner: litellm
      secret:
        name: litellm-db-litellm-secret
  storage:
    size: 2Gi
