apiVersion: v1
kind: ConfigMap
metadata:
  name: searxng-config
  namespace: odysseus
  annotations:
    argocd.argoproj.io/sync-wave: "30"
data:
  settings.yml: |
    use_default_settings: true
    server:
      secret_key: "odysseus-searxng-internal"
    search:
      formats:
        - html
        - json
