apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: external-mygarage-credentials
  namespace: mygarage
  annotations:
    argocd.argoproj.io/sync-wave: "30"
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-cluster
  target:
    name: mygarage-credentials
  data:
    - secretKey: db-url
      remoteRef:
        key: MYGARAGE_DB_URL
