apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - anyuid-rolebinding.yaml
  - postgresql-database.yaml
  - external-mygarage-db-mygarage.yaml
  - external-mygarage-credentials.yaml
  - mygarage-chart-app.yaml
  - ./backup
