apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: doppler-infra
spec:
  provider:
    doppler:
      auth:
        secretRef:
          dopplerToken:
            name: eso-token-infra
            key: dopplerToken
            namespace: external-secrets-operator
