apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: honcho-db-honcho-secret
  namespace: honcho
  annotations:
    argocd.argoproj.io/sync-wave: "30"
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-cluster
  target:
    name: honcho-db-honcho-secret
    template:
      engineVersion: v2
      type: kubernetes.io/basic-auth
      data:
        username: "honcho"
        password: "{{ .password }}"
  data:
    - secretKey: password
      remoteRef:
        key: HONCHO_POSTGRES_USER_PASSWORD
