apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vehicle-pipeline-basic-auth
  namespace: vehicle-pipeline
  annotations:
    argocd.argoproj.io/sync-wave: "30"
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-cluster
  target:
    name: vehicle-pipeline-basic-auth
  data:
    - secretKey: htpasswd
      remoteRef:
        key: VEHICLE_PIPELINE_BASIC_AUTH_HTPASSWD
