apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: external-synology-config
  namespace: synology-csi
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-cluster
  data:
    - secretKey: synoip
      remoteRef:
        key: SYNOLOGY_IP
    - secretKey: synouser
      remoteRef:
        key: SYNOLOGY_CSI_USERNAME
    - secretKey: synopass
      remoteRef:
        key: SYNOLOGY_PASSWORD
  target:
    name: client-info-secret
    template:
      type: Opaque
      data:
        client-info.yml: |
          clients:
            - host: {{ .synoip | toString }}
              port: 5000
              https: false
              username: {{ .synouser | toString }}
              password: {{ .synopass | toString }}
            - host: {{ .synoip | toString }}
              port: 5001
              https: true
              username: {{ .synouser | toString }}
              password: {{ .synopass | toString }}
