apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - machineconfig-iscsi.yaml
  - external-synology-config.yaml
  - external-synology-smb-config.yaml
  - synology-scc.yaml
  - synology-iscsi-storageclass.yaml
  - synology-smb-storageclass.yaml
  - storageclass-nfs.yaml
  - https://raw.githubusercontent.com/SynologyOpenSource/synology-csi/refs/heads/main/deploy/kubernetes/v1.20/controller.yml
  - https://raw.githubusercontent.com/SynologyOpenSource/synology-csi/refs/heads/main/deploy/kubernetes/v1.20/csi-driver.yml
  - https://raw.githubusercontent.com/SynologyOpenSource/synology-csi/refs/heads/main/deploy/kubernetes/v1.20/node.yml
  - https://raw.githubusercontent.com/SynologyOpenSource/synology-csi/refs/heads/main/deploy/kubernetes/v1.20/snapshotter/snapshotter.yaml

patches:
  - target:
      group: apps
      version: v1
      kind: DaemonSet
      name: synology-csi-node
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/1/image
        value: synology/synology-csi@sha256:a9e5bc672a704440e839accb3758c283ffa19ed28930b888985841a0b5dbc134
  - target:
      group: apps
      version: v1
      kind: StatefulSet
      name: synology-csi-controller
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/3/image
        value: synology/synology-csi@sha256:a9e5bc672a704440e839accb3758c283ffa19ed28930b888985841a0b5dbc134
  - target:
      group: apps
      version: v1
      kind: StatefulSet
      name: synology-csi-snapshotter
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/1/image
        value: synology/synology-csi@sha256:a9e5bc672a704440e839accb3758c283ffa19ed28930b888985841a0b5dbc134
