apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: synology-iscsi-storage
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: csi.san.synology.com
parameters:
  csi.storage.k8s.io/fstype: "ext4"
  dsm: 10.10.10.40
  location: /volume1
reclaimPolicy: Delete
allowVolumeExpansion: true
