apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: external-odysseus-credentials
  namespace: odysseus
  annotations:
    argocd.argoproj.io/sync-wave: "30"
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-cluster
  target:
    name: odysseus-credentials
  data:
    - secretKey: ODYSSEUS_ADMIN_PASSWORD
      remoteRef:
        key: ODYSSEUS_ADMIN_PASSWORD
