apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - anyuid-rolebinding.yaml
  - external-odysseus-credentials.yaml
  - searxng-config.yaml
  - imagestream.yaml
  - buildconfig.yaml
  - odysseus-app.yaml
