apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: external-nextcloud-admin
  namespace: nextcloud
  annotations:
    argocd.argoproj.io/sync-wave: "30"
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-cluster
  target:
    name: nextcloud-admin
  data:
    - secretKey: nextcloud-username
      remoteRef:
        key: NEXTCLOUD_ADMIN_USER
    - secretKey: nextcloud-password
      remoteRef:
        key: NEXTCLOUD_ADMIN_PASSWORD
    - secretKey: nextcloud-token
      remoteRef:
        key: NEXTCLOUD_EXPORTER_TOKEN
