apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - anyuid-rolebinding.yaml
  - external-nextcloud-admin.yaml
  - external-nextcloud-mariadb.yaml
  - external-nextcloud-redis.yaml
  - heimdall-rbac.yaml
  - nextcloud-app.yaml
  - servicemonitor.yaml
  - prometheus-rule.yaml
  - bootstrap/serviceaccount.yaml
  - bootstrap/role.yaml
  - bootstrap/rolebinding.yaml
  - bootstrap/external-nextcloud-bootstrap-credentials.yaml
  - bootstrap/configmap-bootstrap-script.yaml
  - bootstrap/job.yaml
