apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-cloudflared-credentials
  namespace: cloudflared
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-cluster
  target:
    name: cloudflared-credentials
  data:
    - secretKey: credentials.json
      remoteRef:
        key: CLOUDFLARED_CREDENTIALS
