apiVersion: batch/v1
kind: CronJob
metadata:
  name: psql-backup
  namespace: template
  annotations:
    argocd.argoproj.io/sync-wave: "200"
spec:
  schedule: "0 3 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: database-psql-backup
          volumes:
            - name: backup
              persistentVolumeClaim:
                claimName: syno-template-db-backup
          containers:
            - name: pg-dump-via-kubectl
              env:
                - name: POSTGRES_USER
                  value: template
                - name: POSTGRES_POSTGRES_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: template-pguser-postgres
                      key: password
              volumeMounts:
                - name: backup
                  mountPath: /backup
              image: quay.io/openshift/origin-cli:4.21
              command: ["/bin/bash", "-c"]
              args:
                - |-
                  set -e

                  echo -----------------------------------
                  echo "Backing up $POSTGRES_USER database"
                  kubectl exec "$POSTGRES_USER"-db-postgresql-0 --container postgresql -- /bin/bash -c "PGPASSWORD=$POSTGRES_POSTGRES_PASSWORD pg_dumpall -U postgres" > /backup/backup.sql
                  echo -----------------------------------
                    ls -lah /backup
                  echo -----------------------------------
          restartPolicy: OnFailure
