apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: syno-db-backup
  namespace: paperless
  annotations:
    argocd.argoproj.io/sync-wave: "200"
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: synology-smb-storage
  resources:
    requests:
      storage: 5Gi
