apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../../templates/psql-backup
  - ../../../../templates/volsync/base
  - ../../../../templates/volsync/backblaze

patches:
  - target:
      group: volsync.backube
      version: v1alpha1
      kind: ReplicationSource
      name: template-backup
    path: database-minio.yaml
  
  - target:
      group: external-secrets.io
      version: v1beta1
      kind: ExternalSecret
      name: external-restic-config-b2
    path: database-minio-secret.yaml

  - target:
      group: volsync.backube
      version: v1alpha1
      kind: ReplicationSource
      name: template-backup-b2
    path: database-backblaze.yaml
  
  - target:
      group: external-secrets.io
      version: v1beta1
      kind: ExternalSecret
      name: external-restic-config-b2
    path: database-backblaze-secret.yaml

  - target:
      group: batch
      version: v1
      kind: CronJob
      name: template-backup
    path: database-cron.yaml

