apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: external-mealie-smtp
  namespace: mealie
  annotations:
    argocd.argoproj.io/sync-wave: "30"
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-cluster
  target:
    name: mealie-smtp-secret
  data:
    - secretKey: SMTP_HOST
      remoteRef:
        key: MAIL_HOST
    - secretKey: SMTP_USER
      remoteRef:
        key: MAIL_USERNAME
    - secretKey: SMTP_PASSWORD
      remoteRef:
        key: MAIL_PASSWORD
    - secretKey: SMTP_FROM_EMAIL
      remoteRef:
        key: MAIL_FROM
