apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: external-mealie-openai
  namespace: mealie
  annotations:
    argocd.argoproj.io/sync-wave: "30"
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-cluster
  target:
    name: mealie-openai-secret
  data:
    - secretKey: OPENAI_API_KEY
      remoteRef:
        key: OPENAI_SHARED_API_KEY
