apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - anyuid-rolebinding.yaml
  - external-secret-openai.yaml
  - external-secret-smtp.yaml
  - mealie-chart-app.yaml
  - namespace.yaml
  - ./backup
