apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: external-tymeslot-credentials
  namespace: tymeslot
  annotations:
    argocd.argoproj.io/sync-wave: "30"
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-cluster
  target:
    name: tymeslot-credentials
  data:
    - secretKey: secret-key-base
      remoteRef:
        key: TYMESLOT_SECRET_KEY_BASE
    - secretKey: data-encryption-key
      remoteRef:
        key: TYMESLOT_DATA_ENCRYPTION_KEY
    - secretKey: db-url
      remoteRef:
        key: TYMESLOT_DB_URL
    - secretKey: smtp-host
      remoteRef:
        key: MAIL_HOST
    - secretKey: smtp-username
      remoteRef:
        key: MAIL_USERNAME
    - secretKey: smtp-password
      remoteRef:
        key: MAIL_PASSWORD
    - secretKey: smtp-from
      remoteRef:
        key: MAIL_FROM
    - secretKey: google-client-id
      remoteRef:
        key: TYMESLOT_GOOGLE_CLIENT_ID
    - secretKey: google-client-secret
      remoteRef:
        key: TYMESLOT_GOOGLE_CLIENT_SECRET
    - secretKey: google-state-secret
      remoteRef:
        key: TYMESLOT_GOOGLE_STATE_SECRET
