apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./backup

  - namespace.yaml
  - anyuid-rolebinding.yaml
  - postgresql-database.yaml
  - external-tymeslot-db-superuser.yaml
  - external-tymeslot-db-owner.yaml
  - external-tymeslot-credentials.yaml
  - tymeslot-chart-app.yaml
