apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: n8n-db-n8n-secret
  namespace: n8n
  annotations:
    argocd.argoproj.io/sync-wave: "30"
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-cluster
  target:
    name: n8n-db-n8n-secret
    template:
      engineVersion: v2
      type: kubernetes.io/basic-auth
      data:
        username: "n8n"
        password: "{{ .password }}"

  data:
    - secretKey: password
      remoteRef:
        key: N8N_POSTGRES_USER_PASSWORD
