apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: fastmail-mcp-credentials
  namespace: n8n
  annotations:
    argocd.argoproj.io/sync-wave: "30"
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-cluster
  data:
    - secretKey: apikey
      remoteRef:
        key: FASTMAIL_API_KEY
