apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: n8n-db
  namespace: n8n
  annotations:
    argocd.argoproj.io/sync-wave: "100"
spec:
  instances: 1
  enablePDB: false

  bootstrap:
    initdb:
      database: n8n
      owner: n8n
      secret:
        name: n8n-db-n8n-secret

  storage:
    size: 5Gi