apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: n8n-db
  namespace: n8n
spec:
  instances: 1

  bootstrap:
    initdb:
      database: n8n
      owner: n8n
      secret:
        name: n8n-db-n8n-secret

  storage:
    size: 5Gi