apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - anyuid-rolebinding.yaml
  - external-tax-agent-credentials.yaml
  - external-tax-agent-db.yaml
  - external-tax-agent-db-connection.yaml
  - postgresql-database.yaml
  - tax-agent-app.yaml
  - networkpolicy.yaml
