apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gitea-db-secret
  namespace: gitea
  annotations:
    argocd.argoproj.io/sync-wave: "30"
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-cluster
  target:
    name: gitea-db-secret
    template:
      engineVersion: v2
      type: kubernetes.io/basic-auth
      data:
        username: "gitea"
        password: "{{ .password }}"
  data:
    - secretKey: password
      remoteRef:
        key: GITEA_POSTGRES_USER_PASSWORD
