apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gitea-admin-secret
  namespace: gitea
  annotations:
    argocd.argoproj.io/sync-wave: "30"
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-cluster
  target:
    name: gitea-admin-secret
    template:
      engineVersion: v2
      data:
        username: "jonas"
        password: "{{ .password }}"
        email: "jonas@famjanz.de"
  data:
    - secretKey: password
      remoteRef:
        key: GITEA_ADMIN_PASSWORD
