apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - postgresql-database.yaml
  - external-gitea-db-secret.yaml
  - external-gitea-admin-secret.yaml
  - external-gitea-ssh-key.yaml
  - gitea-chart-app.yaml
  - ./backup
  - bootstrap-rbac.yaml
  - bootstrap-job.yaml
  - gitea-actions-privileged-clusterrolebinding.yaml
  - gitea-actions-chart-app.yaml
