apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: actual-budget-credentials
  namespace: actual-budget
  annotations:
    argocd.argoproj.io/sync-wave: "30"
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-cluster
  target:
    name: actual-budget-credentials
  data:
    - secretKey: ACTUAL_BUDGET_PASSWORD
      remoteRef:
        key: ACTUAL_BUDGET_PASSWORD
