apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - anyuid-rolebinding.yaml
  - external-actual-budget-credentials.yaml
  - actual-budget-app.yaml
  - ./backup
