apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - anyuid-rolebinding.yaml
  - external-litellm-credentials.yaml
  - external-litellm-db.yaml
  - litellm-config.yaml
  - postgresql-database.yaml
  - litellm-app.yaml
