apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - route.yaml
  - pvc.yaml
  - uploads-pvc.yaml

images:
  - name: ghcr.io/pixeljonas/devland-2027
    newName: ghcr.io/pixeljonas/devland-2027
    digest: sha256:2f2710ed76ab9564826baf1505f5a0193d50336a900d3a3b47ba9f0335818dfa
