apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - route.yaml

images:
  - name: ghcr.io/pixeljonas/devland-2027
    newName: ghcr.io/pixeljonas/devland-2027
    digest: sha256:014225b430405cc5d5f0ca80cae79c72b5d1ca268a89816cb9606142902046eb
