apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: devland-gallery-originals
  namespace: devland
  labels:
    app.kubernetes.io/name: devland
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: lvms-vg1
  resources:
    requests:
      storage: 5Gi
