apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - external-pricing-tool-ghcr-pull.yaml
  - external-pricing-tool-basic-auth.yaml
  - nginx-basic-auth-configmap.yaml
  - pricing-tool-app.yaml
  - route.yaml
