apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: database-
namespace: paperless

resources:
  - ../../../../templates/psql-backup
  - ../../../../templates/volsync/base
  - ../../../../templates/volsync/backblaze

patches:
  - target:
      group: volsync.backube
      version: v1alpha1
      kind: ReplicationSource
      name: backup
    path: minio.yaml
  
  - target:
      group: external-secrets.io
      version: v1beta1
      kind: ExternalSecret
      name: external-restic-config
    path: minio-secret.yaml

  - target:
      group: volsync.backube
      version: v1alpha1
      kind: ReplicationSource
      name: backup-b2
    path: backblaze.yaml
  
  - target:
      group: external-secrets.io
      version: v1beta1
      kind: ExternalSecret
      name: external-restic-config-b2
    path: backblaze-secret.yaml

  - target:
      group: batch
      version: v1
      kind: CronJob
      name: psql-backup
    path: cron.yaml
