apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: backup
  annotations:
    argocd.argoproj.io/sync-wave: "200"
spec:
  sourcePVC: syno-template-backup
  trigger:
    schedule: "0 5 * * *"
  restic:
    pruneIntervalDays: 14
    repository: restic-config-database
    cacheStorageClassName: lvms-vg1
    retain:
      hourly: 1
      daily: 5
      weekly: 4
      monthly: 2
      yearly: 1
    copyMethod: Direct
