name: Validate Manifests
on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803  # v6
      - name: Install yamllint
        run: pip install 'yamllint>=1.25.0'
      - name: Verify Kustomize CLI Installation
        run: |
          which kustomize
          kustomize version
      - name: Validate Manifests
        run: |
          ./scripts/validate_manifests.sh
